import { StyleSheet } from 'react-native';

const lightColors = {
  accent: '#e99314',
  badgeBackground: '#f6f8fc',
  border: '#d7e1f1',
  borderStrong: '#bdcbe0',
  canvas: '#edf3ff',
  danger: '#ae2b2b',
  dangerBorder: '#f0c8c8',
  dangerRipple: '#fde8e8',
  dangerSoft: '#fff0f0',
  gradeBackground: '#f7f9ff',
  gradeBorder: '#c5d4ef',
  gradeMetaBackground: '#fff2d5',
  gradeMetaText: '#8c5a05',
  ink: '#14213d',
  inkSoft: '#53627a',
  inkSubtle: '#5f6f86',
  inputBackground: '#fbfcff',
  placeholderBackground: '#f3f6fc',
  primary: '#2456d6',
  primaryAction: '#2456d6',
  primaryRipple: '#173fae',
  selection: '#2456d6',
  shadow: '#23395f',
  success: '#147a45',
  successBorder: '#bde2cd',
  successSoft: '#e8f7ef',
  surface: '#ffffff',
  surfaceRipple: '#e7edfa',
  white: '#ffffff',
} as const;

const darkColors: AppColors = {
  accent: '#f7bd52',
  badgeBackground: '#162238',
  border: '#34445f',
  borderStrong: '#50617d',
  canvas: '#0b1220',
  danger: '#ffb4b4',
  dangerBorder: '#7e3e46',
  dangerRipple: '#512832',
  dangerSoft: '#351b24',
  gradeBackground: '#14213a',
  gradeBorder: '#405476',
  gradeMetaBackground: '#4a3210',
  gradeMetaText: '#ffd385',
  ink: '#f4f7ff',
  inkSoft: '#c2cde0',
  inkSubtle: '#aebbd0',
  inputBackground: '#101a2d',
  placeholderBackground: '#162238',
  primary: '#9ab4ff',
  primaryAction: '#3568e8',
  primaryRipple: '#2149a9',
  selection: '#9ab4ff',
  shadow: '#000000',
  success: '#8ce0ae',
  successBorder: '#326a4b',
  successSoft: '#143525',
  surface: '#111b2e',
  surfaceRipple: '#273753',
  white: '#ffffff',
};

export type AppColors = {
  [Key in keyof typeof lightColors]: string;
};

const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    flex: { flex: 1 },
    screen: { flex: 1, backgroundColor: colors.canvas },
    scrollContent: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 20,
      paddingVertical: 36,
    },
    mathMotifTop: {
      position: 'absolute',
      top: 36,
      left: -18,
      opacity: 0.08,
      transform: [{ rotate: '-8deg' }],
    },
    mathMotifBottom: {
      position: 'absolute',
      right: -24,
      bottom: 46,
      opacity: 0.09,
      transform: [{ rotate: '7deg' }],
    },
    mathMotifPrimary: {
      color: colors.primary,
      fontSize: 56,
      fontWeight: '900',
      letterSpacing: -3,
    },
    mathMotifSecondary: {
      marginTop: 12,
      marginLeft: 42,
      color: colors.accent,
      fontSize: 30,
      fontWeight: '800',
    },
    shell: { width: '100%', maxWidth: 520 },
    tabletShell: { maxWidth: 720 },
    card: {
      width: '100%',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 28,
      backgroundColor: colors.surface,
      padding: 26,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.18,
      shadowRadius: 30,
      elevation: 6,
    },
    brandLockup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 30,
    },
    brandMark: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 15,
      backgroundColor: colors.primaryAction,
      shadowColor: colors.primaryAction,
      shadowOffset: { width: 0, height: 7 },
      shadowOpacity: 0.24,
      shadowRadius: 14,
      elevation: 4,
    },
    brandMarkText: { color: colors.white, fontSize: 26, fontWeight: '900' },
    brandName: { color: colors.ink, fontSize: 17, fontWeight: '800' },
    brandDetail: {
      marginTop: 2,
      color: colors.inkSubtle,
      fontSize: 13,
    },
    loadingMark: {
      width: 58,
      height: 58,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
      borderRadius: 18,
      backgroundColor: colors.primaryAction,
    },
    loadingMarkText: { color: colors.white, fontSize: 30, fontWeight: '900' },
    loadingPanel: { alignItems: 'center', gap: 14, padding: 32 },
    loadingText: { color: colors.inkSoft, fontSize: 16, fontWeight: '600' },
    title: {
      color: colors.ink,
      fontSize: 34,
      fontWeight: '900',
      letterSpacing: -1,
      lineHeight: 41,
    },
    subtitle: {
      marginTop: 9,
      marginBottom: 26,
      color: colors.inkSoft,
      fontSize: 16,
      lineHeight: 24,
    },
    label: {
      marginBottom: 8,
      color: colors.ink,
      fontSize: 15,
      fontWeight: '700',
    },
    input: {
      minHeight: 54,
      marginBottom: 18,
      borderWidth: 1,
      borderColor: colors.borderStrong,
      borderRadius: 14,
      paddingHorizontal: 16,
      color: colors.ink,
      backgroundColor: colors.inputBackground,
      fontSize: 16,
    },
    primaryButton: {
      minHeight: 54,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
      borderRadius: 15,
      backgroundColor: colors.primaryAction,
      shadowColor: colors.primaryAction,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 14,
      elevation: 3,
    },
    buttonPressed: { opacity: 0.84, transform: [{ translateY: 1 }] },
    buttonDisabled: { opacity: 0.56 },
    primaryButtonText: { color: colors.white, fontSize: 17, fontWeight: '800' },
    secondaryButton: {
      minHeight: 54,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 14,
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: 15,
      backgroundColor: colors.surface,
    },
    secondaryButtonText: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: '800',
    },
    logoutButton: {
      minHeight: 52,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 12,
      borderRadius: 14,
    },
    logoutButtonText: { color: colors.danger, fontSize: 16, fontWeight: '800' },
    errorMessage: {
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.dangerBorder,
      borderRadius: 12,
      padding: 12,
      color: colors.danger,
      backgroundColor: colors.dangerSoft,
      fontSize: 15,
      lineHeight: 21,
    },
    successMessage: {
      marginBottom: 18,
      borderWidth: 1,
      borderColor: colors.successBorder,
      borderRadius: 12,
      padding: 12,
      color: colors.success,
      backgroundColor: colors.successSoft,
      fontSize: 15,
    },
    notice: {
      marginTop: 20,
      color: colors.inkSubtle,
      fontSize: 14,
      lineHeight: 21,
    },
    memberBadge: {
      alignSelf: 'flex-start',
      marginTop: 18,
      marginBottom: 4,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      backgroundColor: colors.badgeBackground,
    },
    memberBadgeLabel: {
      marginBottom: 2,
      color: colors.inkSubtle,
      fontSize: 12,
      fontWeight: '700',
    },
    memberPhone: { color: colors.ink, fontSize: 18, fontWeight: '800' },
    placeholderPanel: {
      marginTop: 24,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 18,
      padding: 20,
      backgroundColor: colors.placeholderBackground,
    },
    placeholderTitle: { color: colors.ink, fontSize: 18, fontWeight: '800' },
    placeholderText: {
      marginTop: 8,
      color: colors.inkSoft,
      fontSize: 15,
      lineHeight: 22,
    },
    gradeList: { marginTop: 24, gap: 13 },
    gradeCard: {
      minHeight: 112,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: colors.gradeBorder,
      borderRadius: 18,
      padding: 18,
      backgroundColor: colors.gradeBackground,
    },
    gradeHeader: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    gradeName: {
      flexShrink: 1,
      color: colors.ink,
      fontSize: 20,
      fontWeight: '900',
    },
    gradeMeta: {
      flexShrink: 0,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
      color: colors.gradeMetaText,
      backgroundColor: colors.gradeMetaBackground,
      fontSize: 12,
      fontWeight: '800',
    },
    gradePrize: {
      marginTop: 10,
      color: colors.primary,
      fontSize: 15,
      fontWeight: '800',
    },
    gradeDescription: {
      marginTop: 6,
      color: colors.inkSoft,
      fontSize: 14,
      lineHeight: 21,
    },
  });

export type AppTheme = {
  colors: AppColors;
  styles: ReturnType<typeof createStyles>;
};

export const lightTheme: AppTheme = {
  colors: lightColors,
  styles: createStyles(lightColors),
};

export const darkTheme: AppTheme = {
  colors: darkColors,
  styles: createStyles(darkColors),
};
